import assert from 'node:assert/strict';
import fs from 'node:fs';
const client=fs.readFileSync('shared/cloud-content.js','utf8');
const control=fs.readFileSync('functions/api/processing/control.js','utf8');
const admin=fs.readFileSync('functions/api/admin/processing-control.js','utf8');
assert.ok(client.includes("/api/admin/processing-control?action=list"));
assert.ok(client.includes("/api/admin/processing-control?action=get"));
assert.ok(control.includes('worker-health'));
assert.ok(control.includes('worker-health'));
assert.ok(admin.includes('listJobSummaries(env.VIDEO_BUCKET'));
assert.equal(client.includes("admin_list_processing_video_groups_v1"),false);
assert.equal(client.includes("supabase.co/functions/v1/video-processing"),false);
console.log('R2 processing queue and admin proxy contract passed.');
