import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const bag=new Map();
const localStorage={getItem:k=>bag.has(k)?bag.get(k):null,setItem:(k,v)=>bag.set(k,String(v)),removeItem:k=>bag.delete(k)};
class CustomEvent{constructor(type,opts={}){this.type=type;this.detail=opts.detail}}
const window={localStorage,CustomEvent,dispatchEvent(){}};
const context=vm.createContext({window,localStorage,CustomEvent,console,setTimeout,clearTimeout});
vm.runInContext(fs.readFileSync(new URL('../shared/content-store.js',import.meta.url),'utf8'),context);
const S=window.ZoContent;
assert.equal(S.listVideos().length,0,'fresh install must not manufacture demonstration videos');
S.importSnapshot(JSON.parse(fs.readFileSync(new URL('fixtures/legacy-content.json',import.meta.url),'utf8')),{type:'test.fixture'});
assert.ok(S,'ZoContent must load');
assert.equal(S.SCHEMA_VERSION,3,'sentence-aware content schema must be V3');
let a=S.audit();
assert.equal(a.ok,true,'seed contract audit must pass');
assert.equal(S.listVideos({publishedOnly:true}).length,8,'student projection should expose only the 8 seeded PUBLISHED videos');
assert.ok(!S.listVideos({publishedOnly:true}).some(v=>v.id===2807),'seed DRAFT video 2807 must not leak into student projection');
const original=S.getVideo(2805);
assert.ok(original.titleZh,'seed video must carry a Chinese title for interface-language switching');
assert.ok(S.listSentences(2805).every(row=>row.keyWords.length&&row.grammar),'every seeded lesson sentence must carry key expressions and matching grammar');
S.saveVideo({...original,title:'Contract Test Title'});
assert.equal(S.getVideo(2805).title,'Contract Test Title','admin update must round-trip');
assert.equal(S.listVideos({publishedOnly:true}).find(v=>v.id===2805).title,'Contract Test Title','student-visible projection must use same record');
const created=S.saveVideo({id:99001,title:'Draft Contract Video',creatorId:'creator-jojo',creator:'Jojo English',level:'A2',status:'DRAFT',pipelineStatus:'READY',mediaUrl:'assets/video/sample_lesson.mp4',tagIds:['daily-life','natural-speech','a2-listening']});
assert.ok(!S.listVideos({publishedOnly:true}).some(v=>v.id===created.id),'draft must not leak to student projection');
S.saveSentence(created.id,{id:'99001-1',order:0,startTime:0,endTime:2.4,english:'Hello from the shared contract.',chinese:'来自共享契约的问候。',keyWords:['shared'],reviewStatus:'APPROVED'});
S.setVideoStatus(created.id,'PUBLISHED');
assert.ok(S.listVideos({publishedOnly:true}).some(v=>v.id===created.id),'published video must appear in student projection');
assert.equal(S.listSentences(created.id).length,1,'sentence must round-trip via shared contract');
assert.equal(Array.from(S.listSentences(created.id)[0].keyWords).join(','),'shared','keyWords must round-trip for cloze authoring');
assert.equal(S.listSentences(created.id)[0].wordTimings.length,5,'word timings must be generated for legacy/plain sentence input');
assert.equal(S.listSentences(created.id)[0].timingSource,'estimated','generated timings must be clearly marked as estimated');
S.saveSentence(created.id,{...S.listSentences(created.id)[0],timingSource:'faster-whisper',wordTimings:[{text:'Hello',start:0,end:.45},{text:'from',start:.45,end:.9},{text:'the',start:.9,end:1.22},{text:'shared',start:1.22,end:1.8},{text:'contract',start:1.8,end:2.4}]});
assert.equal(S.listSentences(created.id)[0].wordTimings[3].word,'shared','authored word timing must round-trip through the shared contract');
assert.equal(S.listSentences(created.id)[0].timingSource,'faster-whisper','precise faster-whisper timing provenance must survive normalization');
assert.throws(()=>S.saveCreator({name:'null'}),/CREATOR_NAME_INVALID/,'placeholder creator names must be rejected');
const temporaryCreator=S.saveCreator({id:'creator-contract-test',name:'Contract Creator',bio:'temporary'});
S.saveVideo({...S.getVideo(created.id),creatorId:temporaryCreator.id,creator:temporaryCreator.name});
assert.throws(()=>S.deleteCreator(temporaryCreator.id),/CREATOR_REPLACEMENT_REQUIRED/,'linked creators require an explicit replacement');
S.deleteCreator(temporaryCreator.id,'creator-jojo');
assert.equal(S.listCreators().some(row=>row.id===temporaryCreator.id),false,'logical deletion must hide creators from active lists');
assert.equal(S.getVideo(created.id).creatorId,'creator-jojo','creator deletion must atomically reassign linked videos');
S.restoreCreator(temporaryCreator.id);
assert.equal(S.listCreators().some(row=>row.id===temporaryCreator.id),true,'logically deleted creators must be restorable');
S.startPipeline(created.id);
let job=S.listJobs().find(j=>j.videoId===created.id);
assert.equal(job.status,'PROCESSING','pipeline must start in isolated job state');
assert.ok(job.steps.some(([name])=>name==='enrich'),'pipeline must include real AI enrichment before review');
assert.throws(()=>S.advancePipeline(created.id),/PIPELINE_SERVER_REQUIRED/,'browser must not advance production jobs');
S.updatePipeline(created.id,{id:job.id,currentStep:'asr',progress:62});
job=S.listJobs().find(j=>j.videoId===created.id);
assert.ok(job.progress>8,'pipeline must advance without rewriting unrelated records');
assert.throws(()=>S.completePipeline(created.id,{video:{mediaUrl:'assets/video/sample_lesson.mp4'},sentences:[]}),/ASR_EMPTY/,'empty transcription must never complete');
S.completePipeline(created.id,{id:job.id,video:{mediaUrl:'assets/video/sample_lesson.mp4'},sentences:[{id:'99001-asr-1',startTime:0,endTime:2.4,english:'A real transcript is required.',chinese:'必须有真实字幕。',keyWords:['real transcript'],grammar:'被动语态表达要求。'}]});
assert.equal(S.getVideo(created.id).status,'REVIEW','real output must wait for human review');
a=S.audit();
assert.equal(a.ok,true,'post-mutation contract audit must still pass');
console.log(JSON.stringify({ok:true,tests:30,videoCount:a.videoCount,publishedCount:a.publishedCount,jobCount:a.jobCount},null,2));
