from pathlib import Path
from html.parser import HTMLParser
import json, os, subprocess, re, sys
root=Path.cwd()
checks=[]
def checked_run(args):
    environment={**os.environ,'NODE_NO_WARNINGS':'1'}
    return subprocess.run(args,capture_output=True,text=True,encoding='utf-8',errors='replace',env=environment)
def add(name,ok,detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':detail})
class P(HTMLParser):
    def __init__(self): super().__init__(); self.ids=[]; self.refs=[]
    def handle_starttag(self,tag,attrs):
        d=dict(attrs)
        if 'id' in d:self.ids.append(d['id'])
        if tag=='script' and d.get('src'):self.refs.append(d['src'])
        if tag=='link' and d.get('href'):self.refs.append(d['href'])
for rel in ['index.html','admin/index.html']:
    p=P();p.feed((root/rel).read_text(encoding='utf-8'))
    dup=sorted({x for x in p.ids if p.ids.count(x)>1})
    add(f'{rel}: unique DOM ids',not dup,','.join(dup))
    missing=[]
    base=(root/rel).parent
    for ref in p.refs:
        if ref.startswith(('http:','https:','#','data:')):continue
        target=(base/ref.split('?')[0]).resolve()
        if not target.exists():missing.append(ref)
    add(f'{rel}: local script/css refs exist',not missing,','.join(missing))
for rel in ['assets/js/app.js','admin/assets/admin.js','shared/content-store.js','shared/supabase-client.js','shared/cloud-content.js','functions/_lib/auth.js','functions/api/session.js','functions/api/media.js','functions/api/admin/uploads/init.js','functions/api/admin/uploads/part.js','functions/api/admin/uploads/complete.js','functions/api/admin/uploads/abort.js']:
    r=checked_run(['node','--check',str(root/rel)])
    add(f'{rel}: JavaScript syntax',r.returncode==0,(r.stderr or '').strip())
student=(root/'index.html').read_text(encoding='utf-8')
app=(root/'assets/js/app.js').read_text(encoding='utf-8')
admin=(root/'admin/assets/admin.js').read_text(encoding='utf-8')
studio_v2=(root/'admin/assets/studio-v2.js').read_text(encoding='utf-8')
studio_server=(root/'services/local-studio/server.py').read_text(encoding='utf-8')
studio_pipeline=(root/'services/local-studio/pipeline.py').read_text(encoding='utf-8')
student_css=(root/'assets/css/app.css').read_text(encoding='utf-8')
admin_css=(root/'admin/assets/admin.css').read_text(encoding='utf-8')
add('student loads shared content contract','shared/content-store.js' in student)
add('student hydrates managed published content','hydrateManagedContent()' in app and 'publishedOnly:true' in app)
add('student resolves active video id dynamically','function activeVideoId()' in app and "progress:'+id" in app)
add('admin can CRUD video records',all(x in admin for x in ['saveVideo','setVideoStatus','openVideoModal']))
add('admin exposes real local pipeline boundary',all(x in admin+studio_v2+studio_server for x in ['startPipeline','process_job','renderPipeline','createJob']))
add('admin exposes subtitle editor',all(x in admin for x in ['renderSubtitleEditor','saveSentence']))
add('admin/student same-origin link exists','../index.html#/home' in (root/'admin/index.html').read_text(encoding='utf-8'))
admin_html=(root/'admin/index.html').read_text(encoding='utf-8')
add('admin has independent authentication gate',all(x in admin_html for x in ['adminAuthGate','adminAuthForm','shared/supabase-client.js']) and all(x in admin for x in ['initAdminAuth','signInPhone','getContext(\'admin\')','profile?.role!==\'admin\'']))
add('student account menu exposes logout/profile/preferences',all(x in student for x in ['data-account-action="logout"','data-account-action="profile"','data-account-action="preferences"']))
add('student account menu has executable session behavior',all(x in app for x in ['function bindAccountUI()','function performLogout()','signinBackdrop']))
add('student preferences dialog is viewport-centered',all(x in student_css for x in ['.backdrop.show{display:grid!important}','right:auto!important','place-items:center']))
add('student streak uses redesigned weekly rhythm UI','streak-v3' in student and '.streak-v3-days' in student_css)
add('admin typography meets readability floor',all(x in admin_css for x in ['.side-nav a{height:44px;font-size:14px','.data-table td{padding:12px 14px;font-size:12px','.page-head p{font-size:14px']))

add('student separates caption display from key-word cloze practice',all(x in student for x in ['data-practice="cloze"','data-caption="english"','data-caption="hidden"']) and all(x in app for x in ['function clozeSentenceHTML','function checkClozeEntry','function sentenceKeywords','function setCaptionMode','function setPracticeMode']))
add('mobile study page uses continuous sentence flow',all(x in student_css for x in ['.mobile-study-tabs{display:none!important}','order:4;display:block!important','.desktop-vocab-mode{display:none!important}']))
add('admin authors per-sentence keyWords',all(x in admin for x in ['keyword-editor','data-field="keyWords"',"keyWords:String(input('keyWords')"]))
add('shared Sentence Contract exposes word-level timings',all(x in (root/'shared/content-store.js').read_text(encoding='utf-8') for x in ['wordTimings','deriveWordTimings','INVALID_WORD_TIMING']))
add('student synchronizes spoken word highlight',all(x in app for x in ['data-word-start','function updateWordTimeline','timing-active']))
add('admin authors word-level timings',all(x in admin for x in ['data-field="wordTimings"','parseWordTimeline','word-timeline-editor']))
add('admin theme is independent from learner theme',all(x in admin for x in ['ADMIN_THEME_KEY',"zs:admin:theme"]) and 'zs:admin:theme' in (root/'admin/index.html').read_text(encoding='utf-8'))
add('subtitle review offers automatic alignment before advanced timing edits',all(x in admin for x in ['timeline-summary','data-check-all-timelines','timeline-advanced']))
add('admin offers AI connection configuration guidance',(root/'README_AI_CONFIGURATION.md').exists() and (root/'.env.example').exists() and 'aiConfigForm' in admin)
add('admin pipeline performs sentence-aware learning analysis',all(x in admin+studio_v2+studio_pipeline for x in ['doLearningAnalysis','learningAnalysis:true','analyzeSentenceLearningFields','sentences','humanReviewRequired']))
add('admin upload captures bilingual title and learning-analysis option',all(x in (root/'admin/index.html').read_text(encoding='utf-8') for x in ['name="titleZh"','name="doLearningAnalysis"']))
add('student switches active video title by interface language',all(x in app for x in ['function localizedVideoTitle','function syncStudyVideoTitle','video.titleZh||video.title']) and 'data-no-ui-translate' in student)
add('learner insight renders every authored key expression',"const keys=sentenceKeywords(d);" in app and "keys.forEach((key,index)=>" in app and "vocab.append(button)" in app and "sentenceKeywords(d).slice(0,3)" not in app)
add('learner typography uses readable 16px support copy',all(x in student_css for x in ['--eastudy-body:19px','.video-page .insight-grid p{font-size:16px!important','.collection-video-info h3{font-size:21px!important']))
add('official Eastudy logo asset is used on every brand surface',all(x in student for x in ['eastudy-logo--top','eastudy-logo--mobile','eastudy-logo--sidebar','eastudy-logo--signin','eastudy-icon.png']) and all(x in (root/'admin/index.html').read_text(encoding='utf-8') for x in ['eastudy-logo--studio','eastudy-icon.png']) and (root/'assets/images/eastudy-logo.png').exists() and (root/'assets/images/eastudy-icon.png').exists())
add('supplied VIP artwork is used on all membership surfaces',all((root/'assets/images'/name).exists() for name in ['eastudy-vip-dark.png','eastudy-vip-light.png']) and all(x in student_css for x in ["--eastudy-vip-logo:url('../images/eastudy-vip-light.png')","--eastudy-vip-logo:url('../images/eastudy-vip-dark.png')",'.vip-badge,','.vip-emblem,']))
add('homepage upgrade promotion card is removed','home-pro-card' not in student and '升级至 Eastudy Pro' not in student)
add('supplied motivation card switches with learner theme',all((root/'assets/images'/name).exists() for name in ['eastudy-quote-light.webp','eastudy-quote-dark.webp']) and all(x in student_css for x in ["--eastudy-quote-art:url('../images/eastudy-quote-light.webp')","--eastudy-quote-art:url('../images/eastudy-quote-dark.webp')",'aspect-ratio:var(--eastudy-quote-ratio)']))
add('desktop study workspace has no page or left-pane scrolling',all(x in student_css for x in ['@media(min-width:851px)','height:calc(100vh - 58px)!important','overflow:hidden!important','only subtitles scroll']))
add('adjacent key expressions receive distinct colour tones',all(x in app for x in ["keywordTone=(keywordTone%4)+1","cls.push('keyword-tone-'+(tone||keywordTone))","renderToken(words[n].raw,phrase.key,n,n,true,keywordTone)"]) and all(f'keyword-tone-{i}' in student_css for i in range(1,5)))
add('vocabulary state persists across reloads',all(x in app for x in ["Storage.get('vocabMeta'","Storage.set('vocabMeta'",'nextReviewAt','correctStreak']))
add('vocabulary review flow reveals then grades recall',all(x in student for x in ['vocabReviewPanel','vocabReviewReveal','vocabReviewAgain','vocabReviewKnown']) and all(x in app for x in ['openVocabReview','revealVocabReview','gradeVocabReview']))
add('vocabulary statistics are data driven',all(x in student for x in ['vocabWeeklyCount','vocabDueCount','vocabMasteryRate']) and 'function updateVocabStats' in app)
add('first visit opens responsive authentication gateway',all(x in student for x in ['auth-gateway','data-auth-tab="login"','data-auth-tab="register"','signinInviteCode','authSuccess']) and all(x in app for x in ['initStudentAuth','window.EastudyAuth','signInAccount','registerWithInvite','bindAuthGateway']))
add('mobile app navigation includes dedicated account route','data-route="/me"' in student and 'id="profilePage"' in student and "path==='/me'" in app)
add('mobile header no longer exposes account avatar','class="mobile-avatar"' not in student)
add('home carousel supports phone swipe gestures',all(x in app for x in ["addEventListener('pointerdown'","addEventListener('pointerup'",'Math.abs(dx)>45']))
add('mobile categories expose view all action','mobile-category-heading' in student and 'data-route="/videos">查看全部' in student)
add('home recommended creators are de-duplicated and mobile safe','new Map(UI_CREATORS.filter' in app and all(x in student_css for x in ['.home-creator-copy','.home-creator .creator-mini-follow{position:static!important']))
add('requested mobile priority explanation is removed','你的进度和继续学习入口放在第一屏，不再沉到页面底部。' not in student)
add('web deployment exposes /admin entry',(root/'README_WEB_DEPLOY.md').exists() and '/admin /admin/index.html 200' in (root/'_redirects').read_text(encoding='utf-8'))
cloud=(root/'shared/cloud-content.js').read_text(encoding='utf-8')
cloud_sql=(root/'supabase/migrations/20260908101008_cloud_content_and_admin.sql').read_text(encoding='utf-8')
function_auth=(root/'functions/_lib/auth.js').read_text(encoding='utf-8')
media_function=(root/'functions/api/media.js').read_text(encoding='utf-8')
add('admin supports authenticated R2 multipart upload',all(x in cloud for x in ['/api/admin/uploads/init','/api/admin/uploads/part','/api/admin/uploads/complete','Authorization']))
add('media delivery requires an active administrator',all(x in media_function for x in ['requireAdmin(request, env)','VIDEO_BUCKET','Range','Content-Range']))
add('Cloudflare upload gate checks administrator role',all(x in function_auth for x in ['requireAdmin','PROFILE_LOOKUP_FAILED','ADMIN_REQUIRED']))
add('Supabase content publishing is authenticated and atomic',all(x in cloud_sql for x in ['private.content_snapshots','admin_publish_content_snapshot','get_published_content','revision = private.content_snapshots.revision + 1']))
learning_sql=(root/'supabase/migrations/20260908114654_learning_goal_autoplay.sql').read_text(encoding='utf-8')
learning_queue=(root/'shared/learning-queue.js').read_text(encoding='utf-8')
add('learner goal profile is isolated by Supabase RLS',all(x in learning_sql for x in ['learner_goal_profiles','user_id = auth.uid()','primary_goal_id','onboarding_version']))
add('student exposes goal onboarding and explicit autoplay controls',all(x in student for x in ['goalOnboarding','homeGoalStart','nextLessonCountdown','cancelNextLesson','queueLoopToggle']) and all(x in app for x in ['maybeShowGoalOnboarding','playNextQueueLesson','ensurePlaybackCountdown']))
add('autoplay queue filters reviewed target content and supports fixed collections',all(x in learning_queue for x in ['mappedGoalIds','eligibleVideos','collectionId','queue?.loop']))
cloud_run=checked_run(['node',str(root/'audit/processing_r2_control_test.mjs')])
add('R2 processing and cloud content contract regression',cloud_run.returncode==0,(cloud_run.stdout+cloud_run.stderr).strip())
run=checked_run(['node',str(root/'audit/runtime_contract_test.mjs')])
add('runtime shared-contract regression',run.returncode==0,(run.stdout+run.stderr).strip())
auth_run=checked_run(['node',str(root/'audit/auth_contract_test.mjs')])
add('student OTP and password contract regression',auth_run.returncode==0,(auth_run.stdout+auth_run.stderr).strip())
learning_run=checked_run(['node',str(root/'audit/learning_queue_contract_test.mjs')])
add('learning queue and countdown contract regression',learning_run.returncode==0,(learning_run.stdout+learning_run.stderr).strip())
report={'ok':all(c['ok'] for c in checks),'passed':sum(c['ok'] for c in checks),'total':len(checks),'checks':checks}
(root/'audit/AUDIT_REPORT.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
md=['# Eastudy Composite V1 Beta 6.25.2 — Audit Report','',f"Result: **{'PASS' if report['ok'] else 'FAIL'}**  ({report['passed']}/{report['total']})",'']
for c in checks:md.append(f"- {'PASS' if c['ok'] else 'FAIL'} — {c['name']}"+(f" — {c['detail']}" if c['detail'] else ''))
(root/'audit/AUDIT_REPORT.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
sys.exit(0 if report['ok'] else 1)
