import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const bag=new Map(),localStorage={getItem:k=>bag.get(k)??null,setItem:(k,v)=>bag.set(k,v)};
class CustomEvent{constructor(type,options){this.type=type;this.detail=options?.detail}}
let jobs=[],remoteCalls=0;
const window={location:{hostname:'localhost'},dispatchEvent(){},EastudyStudioClient:{listJobs:async()=>({jobs})},EastudyAuth:{client(){remoteCalls++;throw Error('UNEXPECTED_CLOUD_CALL')}}};
const document={readyState:'loading',addEventListener(){},querySelector:()=>null};
const ctx=vm.createContext({window,document,localStorage,CustomEvent,console,setTimeout,clearTimeout,location:window.location});
vm.runInContext(fs.readFileSync('shared/content-store.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('admin/assets/studio-v2.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('shared/cloud-content.js','utf8'),ctx);
const S=window.ZoContent,Studio=window.EastudyStudioV2;
const video={id:456,title:'真实视频',status:'REVIEW',pipelineStatus:'READY',localStudioJobId:'worker-456',mediaUrl:'/real.mp4',creatorId:'creator-jojo'};
S.saveVideo(video);
jobs=[{id:'worker-456',status:'ERROR',metadata:{localVideoId:456,title:'迟到的结果'},error:{message:'late'}}];
S.deleteVideo(456);await Studio.syncJobs();assert.equal(S.getVideo(456),null,'worker must not recreate trashed content');
S.restoreVideo(456);S.saveVideo({id:456,title:'人工修改的草稿'});await Studio.syncJobs();
assert.equal(S.getVideo(456).title,'人工修改的草稿');assert.equal(S.getVideo(456).pipelineStatus,'READY');
jobs=[{id:'older-worker',status:'ERROR',metadata:{localVideoId:456},error:{message:'stale'}}];await Studio.syncJobs();
assert.equal(S.getVideo(456).pipelineStatus,'READY','wrong job cannot overwrite existing video');
assert.equal(S.acceptsJob(456,'worker-456'),false);S.allowJobRetry(456,'worker-456');
assert.equal(S.acceptsJob(456,'worker-456'),true,'only intentional retry permits the blocked job again');
const cloud=window.EastudyCloudContent;
assert.equal((await cloud.pullAdmin()).snapshot,null);assert.equal((await cloud.pullPublished()).snapshot,null);
assert.match((await cloud.saveDraft(S.snapshot())).error.message,/LOCAL_CONTENT_CLOUD_WRITE_DISABLED/);
assert.match((await cloud.publish(S.snapshot())).error.message,/LOCAL_CONTENT_CLOUD_WRITE_DISABLED/);
assert.equal(remoteCalls,0);
console.log('Studio deletion: actual syncJobs ignores trashed/restored/stale jobs; local cloud boundary makes zero RPCs.');
