const headers={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'apikey, authorization, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS',
  'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'
};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});
const required=(name)=>{const value=String(Deno.env.get(name)||'').trim();if(!value)throw new Error(`CONFIG_${name}_MISSING`);return value};

async function request(path,init={}){const key=required('SUPABASE_SERVICE_ROLE_KEY'),response=await fetch(required('SUPABASE_URL')+path,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}}),payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.message||payload.msg||payload.code||`UPSTREAM_${response.status}`);error.status=response.status;throw error}return Array.isArray(payload)?payload[0]:payload}
const serviceRpc=(name,input)=>request(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(input||{})});
async function userRpc(token,name,input){const response=await fetch(required('SUPABASE_URL')+`/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:required('SUPABASE_SERVICE_ROLE_KEY'),Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(input||{})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.code||`RPC_${response.status}`);return Array.isArray(payload)?payload[0]:payload}
async function passwordGrant(identity,password){const response=await fetch(required('SUPABASE_URL')+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:required('SUPABASE_SERVICE_ROLE_KEY'),'Content-Type':'application/json'},body:JSON.stringify({...identity,password})}),payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error_description||payload.msg||'INVALID_LOGIN');error.status=response.status;throw error}return payload}
async function discardSession(session){const token=String(session?.access_token||'');if(!token)return;const response=await fetch(required('SUPABASE_URL')+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:required('SUPABASE_SERVICE_ROLE_KEY'),Authorization:`Bearer ${token}`}});if(!response.ok&&response.status!==401)throw new Error(`AUTH_LOGOUT_${response.status}`)}

async function handle(req){const text=await req.text();if(text.length>8192)return json({error:'ACCOUNT_FORMAT_INVALID'},400);let input;try{input=JSON.parse(text||'{}')}catch{return json({error:'ACCOUNT_FORMAT_INVALID'},400)}const account=canonicalLoginKey(input.account),password=String(input.password||''),action=input.action==='activate'?'activate':'login';if(!account||password.length<6||password.length>128)return json({error:'ACCOUNT_FORMAT_INVALID'},400);if(action==='activate'&&(String(input.inviteCode||'').trim().length<12||String(input.inviteCode||'').trim().length>80))return json({error:'ACTIVATION_INPUT_INVALID'},400);
  let session=null,delivered=false;
  try{const resolved=await serviceRpc('resolve_account_login_v2',{p_account:account});if(resolved?.state==='NOT_FOUND')return json({error:'INVALID_LOGIN'},401);if(resolved?.state==='DISABLED')return json({error:'ACCOUNT_UNAVAILABLE'},403);const authIdentity=identityFromResolution(resolved);if(!authIdentity)throw new Error('IDENTITY_UNAVAILABLE');session=await passwordGrant(authIdentity,password);if(session?.user?.id!==resolved.userId)throw new Error('IDENTITY_MISMATCH');let access=await serviceRpc('service_get_user_learning_access_v2',{p_user_id:session.user.id});if(action==='activate'){if(access?.kind==='ADMIN')return json({error:'ADMIN_NO_REDEMPTION_REQUIRED'},409);if(!['VIP_REQUIRED','VIP_EXPIRED','OK'].includes(String(access?.reason||'')))return json({error:access?.reason||'LOGIN_SERVICE_UNAVAILABLE'},403);await userRpc(session.access_token,'redeem_activation_code',{p_code:String(input.inviteCode||'').trim()});access=await serviceRpc('service_get_user_learning_access_v2',{p_user_id:session.user.id})}if(access?.canEnterLearning!==true)return json({error:access?.reason||'ACCESS_DENIED',access:{reason:access?.reason||'ACCESS_DENIED',expiresAt:access?.expiresAt||null}},403);delivered=true;return json({session,access})}catch(error){const [status,code]=publicAuthFailure(error);console.warn('learner auth failed',code);return json({error:code},status)}finally{if(session&&!delivered)await discardSession(session).catch(error=>console.warn('learner auth session cleanup failed',String(error?.message||error)))}}

Deno.serve(req=>req.method==='OPTIONS'?new Response(null,{status:204,headers}):req.method==='POST'?handle(req):json({error:'METHOD_NOT_ALLOWED'},405));
import { publicAuthFailure } from '../_shared/auth-errors.js';
import { canonicalLoginKey, identityFromResolution } from '../_shared/login-identity.js';
